/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
export type EXCELCBTCbtLearningHistoriesExcelGetParams = {
  /**
   * 学年
   */
  grade?: number | null;
  /**
   * クラス名
   */
  class_name?: string | null;
  /**
   * CBT種別ID
   */
  cbt_category_id?: number | null;
};

export type CsvMovieLearningHistoriesCsvGetParams = {
  /**
   * 学年
   */
  grade?: number | null;
  /**
   * クラス名
   */
  class_name?: string | null;
  /**
   * ユーザUUID
   */
  user_uuid?: string | null;
  /**
   * 期間開始日
   */
  from_date: Date;
  /**
   * 期間終了日
   */
  to_date: Date;
};

export type WordsLookedUpRankingGetParams = {
  /**
   * 対象名
   */
  target_name: string;
  /**
   * 月指定
   */
  term_name: string;
};

export type CsvDictionaryKanjiLearningHistoriesCsvGetParams = {
  /**
   * 学年
   */
  grade?: number | null;
  /**
   * クラス名
   */
  class_name?: string;
};

export type DictionaryKanjiLearningHistoriesGetParams = {
  /**
   * 学年
   */
  grade?: number | null;
  /**
   * クラス名
   */
  class_name?: string;
  /**
   * ページ番号
   */
  page: number;
};

export type CsvDictionaryJapaneseLearningHistoriesCsvGetParams = {
  /**
   * 学年
   */
  grade?: number | null;
  /**
   * クラス名
   */
  class_name?: string;
};

export type DictionaryJapaneseLearningHistoriesGetParams = {
  /**
   * 学年
   */
  grade?: number | null;
  /**
   * クラス名
   */
  class_name?: string;
  /**
   * ページ番号
   */
  page: number;
};

export type CsvKanjiSkillTestLearningHistoriesCsvGetParams = {
  /**
   * 学年
   */
  grade?: number | null;
  /**
   * クラス名
   */
  class_name?: string;
  /**
   * 学年・学期・上下のID
   */
  category_id?: number;
  /**
   * 単元ID
   */
  teaching_unit?: number;
};

export type CsvKanjiSkillLearningHistoriesCsvGetParams = {
  /**
   * 学年
   */
  grade?: number | null;
  /**
   * クラス名
   */
  class_name?: string;
  /**
   * ユーザUUID
   */
  user_uuid?: string;
  /**
   * 期間開始日
   */
  from_date: Date;
  /**
   * 期間終了日
   */
  to_date: Date;
  /**
   * 学年・学期・上下のID
   */
  category_id?: number;
  /**
   * 時間帯
   */
  time_slot?: number;
};

export type KanjiSkillTestLearningHistoriesGetParams = {
  /**
   * 学年
   */
  grade?: number | null;
  /**
   * クラス名
   */
  class_name?: string;
  /**
   * 学年・学期・上下のID
   */
  category_id?: number;
  /**
   * 単元ID
   */
  teaching_unit?: number;
  /**
   * ページ番号
   */
  page: number;
};

export type KanjiSkillLearningHistoriesGetParams = {
  /**
   * 学年
   */
  grade?: number | null;
  /**
   * クラス名
   */
  class_name?: string;
  /**
   * ユーザUUID
   */
  user_uuid?: string;
  /**
   * 期間開始日
   */
  from_date: Date;
  /**
   * 期間終了日
   */
  to_date: Date;
  /**
   * 学年・学期・上下のID
   */
  category_id?: number;
  /**
   * 時間帯
   */
  time_slot?: number;
};

export type CsvRomajiSkillLearningHistoriesCsvGetParams = {
  /**
   * 学年
   */
  grade?: number | null;
  /**
   * クラス
   */
  class_name?: string;
  /**
   * ユーザUUID
   */
  user_uuid?: string;
  /**
   * 期間開始日
   */
  from_date: Date;
  /**
   * 期間終了日
   */
  to_date: Date;
  /**
   * 時間帯
   */
  time_slot?: number;
};

export type RomajiSkillLearningHistoriesGetParams = {
  /**
   * 学年
   */
  grade?: number | null;
  /**
   * クラス
   */
  class_name?: string;
  /**
   * ユーザUUID
   */
  user_uuid?: string;
  /**
   * 期間開始日
   */
  from_date: Date;
  /**
   * 期間終了日
   */
  to_date: Date;
  /**
   * 時間帯
   */
  time_slot?: number;
};

export type MunicipalitiesSchoolsGetParams = {
  /**
   * 市区町村ID
   */
  type?: number | null;
};

export type MunicipalitiesGetParams = {
  /**
   * 都道府県ID
   */
  type: number;
};

export type SchoolClassesGetParams = {
  /**
   * 取得タイプ
   */
  type: number;
  /**
 * 
        参照元アプリケーション
        0: トモプラホーム
        1: 光村の国語映像資料 トモプラムービー
        2: 形成的評価 きそのたしかめCBT 国語
        3: 光村の単元テスト 到達度評価シート 国語
        4: デジタル小学新国語辞典
        5: デジタル小学新漢字辞典
        6: あかねこローマ字スキルコネクト
        7: あかねこローマ字スキルコネクト タイピングチャレンジ
        8: あかねこ漢字スキルコネクト光村図書版
        9: あかねこ漢字スキルコネクト東京書籍版
        10: あかねこ漢字スキルコネクト教育出版版
        11: あかねこひらがな・すうじスキルコネクト光村図書版
        12: あかねこひらがな・すうじスキルコネクト東京書籍版
        13: あかねこひらがな・すうじスキルコネクト教育出版版
        14: あかねこカタカナスキルコネクト
        15: あかねこ計算スキルコネクト標準版
        16: あかねこ計算スキルコネクト東京書籍版
        17: あかねこ計算スキルコネクト啓林館版
        
 */
  referrer_application: number;
};

export type UsersMeGetParams = {
  /**
 * 
        参照元アプリケーション
        0: トモプラホーム
        1: 光村の国語映像資料 トモプラムービー
        2: 形成的評価 きそのたしかめCBT 国語
        3: 光村の単元テスト 到達度評価シート 国語
        4: デジタル小学新国語辞典
        5: デジタル小学新漢字辞典
        6: あかねこローマ字スキルコネクト
        7: あかねこローマ字スキルコネクト タイピングチャレンジ
        8: あかねこ漢字スキルコネクト光村図書版
        9: あかねこ漢字スキルコネクト東京書籍版
        10: あかねこ漢字スキルコネクト教育出版版
        11: あかねこひらがな・すうじスキルコネクト光村図書版
        12: あかねこひらがな・すうじスキルコネクト東京書籍版
        13: あかねこひらがな・すうじスキルコネクト教育出版版
        14: あかねこカタカナスキルコネクト
        15: あかねこ計算スキルコネクト標準版
        16: あかねこ計算スキルコネクト東京書籍版
        17: あかねこ計算スキルコネクト啓林館版
        
 */
  referrer_application: number;
};

export type UsersChildrenGetParams = {
  /**
 * 
        参照元アプリケーション
        0: トモプラホーム
        1: 光村の国語映像資料 トモプラムービー
        2: 形成的評価 きそのたしかめCBT 国語
        3: 光村の単元テスト 到達度評価シート 国語
        4: デジタル小学新国語辞典
        5: デジタル小学新漢字辞典
        6: あかねこローマ字スキルコネクト
        7: あかねこローマ字スキルコネクト タイピングチャレンジ
        8: あかねこ漢字スキルコネクト光村図書版
        9: あかねこ漢字スキルコネクト東京書籍版
        10: あかねこ漢字スキルコネクト教育出版版
        11: あかねこひらがな・すうじスキルコネクト光村図書版
        12: あかねこひらがな・すうじスキルコネクト東京書籍版
        13: あかねこひらがな・すうじスキルコネクト教育出版版
        14: あかねこカタカナスキルコネクト
        15: あかねこ計算スキルコネクト標準版
        16: あかねこ計算スキルコネクト東京書籍版
        17: あかねこ計算スキルコネクト啓林館版
        
 */
  referrer_application: number;
  /**
   * 学年
   */
  grade?: number | null;
  /**
   * クラス
   */
  class_name?: string | null;
};

export interface LibsDomainModelInterfaceWordGetWordsLookedUpRankingResponse {
  first: string;
  second: string;
  third: string;
}

export interface LibsDomainModelInterfaceWordGetWordsLookedUpRandomResponse {
  words1: Words;
  words2: Words;
  words3: Words;
  words4: Words;
  words5: Words;
  words6: Words;
}

export interface LibsDomainModelInterfaceUserUpdateTokenResponse {
  success: string;
}

export interface LibsDomainModelInterfaceUserUpdateTokenRequest {
  /** 
        参照元アプリケーション
        0: トモプラホーム
        1: 光村の国語映像資料 トモプラムービー
        2: 形成的評価 きそのたしかめCBT 国語
        3: 光村の単元テスト 到達度評価シート 国語
        4: デジタル小学新国語辞典
        5: デジタル小学新漢字辞典
        6: あかねこローマ字スキルコネクト
        7: あかねこローマ字スキルコネクト タイピングチャレンジ
        8: あかねこ漢字スキルコネクト光村図書版
        9: あかねこ漢字スキルコネクト東京書籍版
        10: あかねこ漢字スキルコネクト教育出版版
        11: あかねこひらがな・すうじスキルコネクト光村図書版
        12: あかねこひらがな・すうじスキルコネクト東京書籍版
        13: あかねこひらがな・すうじスキルコネクト教育出版版
        14: あかねこカタカナスキルコネクト
        15: あかねこ計算スキルコネクト標準版
        16: あかねこ計算スキルコネクト東京書籍版
        17: あかねこ計算スキルコネクト啓林館版
         */
  referrer_application: number;
}

export interface LibsDomainModelInterfaceUserUpdateThemeColorResponse {
  id: number;
  theme_color: number;
}

export interface LibsDomainModelInterfaceUserUpdateThemeColorRequest {
  /** テーマカラーID */
  theme_color: number;
}

export interface LibsDomainModelInterfaceUserUpdateProfileResponse {
  id: number;
  nick_name: string;
  profile_icon: number;
}

export interface LibsDomainModelInterfaceUserUpdateProfileRequest {
  /** ニックネーム */
  nick_name: string;
  /** プロフィール画像ID */
  profile_icon: number;
}

export interface LibsDomainModelInterfaceUserUpdatePasswordResponse {
  /** ユーザUUID */
  success: string;
}

export interface LibsDomainModelInterfaceUserUpdatePasswordRequest {
  /** 現在のパスワード */
  password: string;
  /** 新しいパスワード */
  password_new: string;
}

export interface LibsDomainModelInterfaceUserResetPasswordResponse {
  /** ユーザUUID */
  success: string;
}

export interface LibsDomainModelInterfaceUserResetPasswordRequest {
  /** ワンタイムコード */
  onetime_code: string;
  /** 新しいパスワード */
  password_new: string;
}

export type LibsDomainModelInterfaceUserGetMyInfoResponseUser =
  | UserCore[]
  | null;

export type LibsDomainModelInterfaceUserGetMyInfoResponseSchoolClass =
  | SchoolClass[]
  | null;

export type LibsDomainModelInterfaceUserGetMyInfoResponseGrade = number | null;

export type LibsDomainModelInterfaceUserGetMyInfoResponseClassName =
  | string
  | null;

export interface LibsDomainModelInterfaceUserGetMyInfoResponse {
  class_name: LibsDomainModelInterfaceUserGetMyInfoResponseClassName;
  grade: LibsDomainModelInterfaceUserGetMyInfoResponseGrade;
  last_login_date: Date;
  license: LicenseEntity[];
  nick_name: string;
  preference: UserPreferenceEntity;
  school_class?: LibsDomainModelInterfaceUserGetMyInfoResponseSchoolClass;
  school_id: string;
  time_difference_from_utc: number;
  user?: LibsDomainModelInterfaceUserGetMyInfoResponseUser;
  user_type: number;
  user_uuid: string;
}

export interface LibsDomainModelInterfaceUserGetChildrenListResponse {
  children: Children[];
}

export interface LibsDomainModelInterfaceToppageGetToppageForTeachersResponse {
  graph_data_study_time: StudyTime[];
  notice: string;
  number_cbt: number;
  number_japanese_dictionary: number;
  number_kanji_dictionary: number;
  number_kanji_skill: number;
  preferences: UserPreferenceEntity;
  total_number_logins: number;
  total_study_time: number;
}

export interface LibsDomainModelInterfaceToppageGetToppageForChildrenResponse {
  graph_data_study_time: StudyTime[];
  login_calendar: LoginCalendar;
  notice: string;
  number_japanese_dictionary: number;
  number_kanji_dictionary: number;
  number_kanji_skill: number;
  preferences: UserPreferenceEntity;
  total_number_logins: number;
  total_study_time: number;
}

export interface LibsDomainModelInterfaceSchoolGetSchoolsResponse {
  /** 学校名リスト */
  school_name: string[];
}

export interface LibsDomainModelInterfaceSchoolGetSchoolClassResponse {
  /** 学校情報 */
  school_class: SchoolClass[];
}

export interface LibsDomainModelInterfaceSchoolGetMunicipalitiesResponse {
  /** 市区町村リスト */
  municipalities: Municipalities[];
}

export type LibsDomainModelInterfaceRomajiLearningHistoryUserUuid =
  | string
  | null;

export type LibsDomainModelInterfaceRomajiLearningHistoryGrade = number | null;

export type LibsDomainModelInterfaceRomajiLearningHistoryClassName =
  | string
  | null;

export interface LibsDomainModelInterfaceRomajiLearningHistory {
  average_keystroke_speed: number;
  average_time_step_1: number;
  average_time_step_2: number;
  average_time_step_3: number;
  average_time_step_4: number;
  class_name?: LibsDomainModelInterfaceRomajiLearningHistoryClassName;
  date: Date;
  grade?: LibsDomainModelInterfaceRomajiLearningHistoryGrade;
  total_keystrokes: number;
  total_number: number;
  user_uuid?: LibsDomainModelInterfaceRomajiLearningHistoryUserUuid;
}

export interface LibsDomainModelInterfaceRomajiGetRomajiSkillLearningHistoriesResponse {
  learning_histories: LibsDomainModelInterfaceRomajiLearningHistory[];
}

export interface LibsDomainModelInterfaceNoticeGetNoticeResponse {
  /** お知らせ内容 */
  notice: string;
}

export interface LibsDomainModelInterfaceMailSendResetPasswordURLResponse {
  /** ユーザUUID */
  success: string;
}

export interface LibsDomainModelInterfaceMailSendResetPasswordURLRequest {
  /** メールアドレス */
  mail_address: string;
}

export interface LibsDomainModelInterfaceMailSendMailResponse {
  message?: unknown;
}

export interface LibsDomainModelInterfaceMailSendMailRequest {
  /** メール内容 */
  mail_contents: string;
  /** メール送信コード */
  mail_send_code: string;
  /** 送信タイプ 1: 紙付録ライセンス発行申請 2: 保護者同意 */
  send_type: number;
}

export interface LibsDomainModelInterfaceMailIssueMailSendCodeResponse {
  /** メール送信コード */
  mail_send_code: string;
}

export interface LibsDomainModelInterfaceKanjiRegisterNewWrittenKanjiResponse {
  success: string;
}

export interface LibsDomainModelInterfaceKanjiRegisterNewWrittenKanjiRequest {
  user_uuid: string;
  written_kanji: string;
}

export interface LibsDomainModelInterfaceKanjiLearningHistory {
  daily_data: DailyData[];
  school_class: SchoolClass;
  user_uuid: string;
}

export interface LibsDomainModelInterfaceKanjiGetKanjiSkillTestLearningHistoriesResponse {
  category: Category[];
  learning_histories: LearningHistoryForTest[];
}

export interface LibsDomainModelInterfaceKanjiGetKanjiSkillLearningHistoriesResponse {
  category: Category[];
  learning_histories: LibsDomainModelInterfaceKanjiLearningHistory[];
}

export interface LibsDomainModelInterfaceDictionaryGetKanjiDictionaryLearningHistoriesResponse {
  learning_histories: KanjiDictionaryKLearningHistory[];
}

export interface LibsDomainModelInterfaceDictionaryGetJapaneseDictionaryLearningHistoriesResponse {
  learning_histories: JapaneseDictionaryLearningHistory[];
  words_looked_up_random: WordsLookedUpRandom[];
  words_looked_up_ranking: WordsLookedUpRanking[];
}

export interface LibsDomainModelInterfaceCbtGetCBTCategoriesResponse {
  cbt_categories: CBTCategory[];
}

export type LibsDomainModelInterfaceAuthUpdateAccountResponseStartDate =
  Date | null;

export type LibsDomainModelInterfaceAuthUpdateAccountResponseExpirationDate =
  Date | null;

export interface LibsDomainModelInterfaceAuthUpdateAccountResponse {
  expiration_date: LibsDomainModelInterfaceAuthUpdateAccountResponseExpirationDate;
  release_code_user_uuid: string;
  start_date: LibsDomainModelInterfaceAuthUpdateAccountResponseStartDate;
}

/**
 * 解除コード
 */
export type LibsDomainModelInterfaceAuthUpdateAccountRequestReleaseCode =
  | string
  | null;

export interface LibsDomainModelInterfaceAuthUpdateAccountRequest {
  /** 
        参照元アプリケーション
        0: トモプラホーム
        1: 光村の国語映像資料 トモプラムービー
        2: 形成的評価 きそのたしかめCBT 国語
        3: 光村の単元テスト 到達度評価シート 国語
        4: デジタル小学新国語辞典
        5: デジタル小学新漢字辞典
        6: あかねこローマ字スキルコネクト
        7: あかねこローマ字スキルコネクト タイピングチャレンジ
        8: あかねこ漢字スキルコネクト光村図書版
        9: あかねこ漢字スキルコネクト東京書籍版
        10: あかねこ漢字スキルコネクト教育出版版
        11: あかねこひらがな・すうじスキルコネクト光村図書版
        12: あかねこひらがな・すうじスキルコネクト東京書籍版
        13: あかねこひらがな・すうじスキルコネクト教育出版版
        14: あかねこカタカナスキルコネクト
        15: あかねこ計算スキルコネクト標準版
        16: あかねこ計算スキルコネクト東京書籍版
        17: あかねこ計算スキルコネクト啓林館版
         */
  referrer_application: number;
  /** 解除コード */
  release_code?: LibsDomainModelInterfaceAuthUpdateAccountRequestReleaseCode;
  /** 解除コード使用ユーザUUID */
  release_code_user_uuid?: string;
}

export interface LibsDomainModelInterfaceAuthLogoutResponse {
  /** ユーザUUID */
  success: string;
}

export interface LibsDomainModelInterfaceAuthLoginResponse {
  /** ユーザUUID */
  user_uuid: string;
}

/**
 * SSO 認証結果のトークン
 */
export type LibsDomainModelInterfaceAuthLoginSSORequestCode = string | null;

export interface LibsDomainModelInterfaceAuthLoginSSORequest {
  /** SSO 認証結果のトークン */
  code: LibsDomainModelInterfaceAuthLoginSSORequestCode;
}

/**
 * パスワード
 */
export type LibsDomainModelInterfaceAuthLoginRequestPassword = string | null;

/**
 * 認証コード (2次元バーコードでログイン使用する際に使用)
 */
export type LibsDomainModelInterfaceAuthLoginRequestAuthenticationCode =
  | string
  | null;

/**
 * ユーザーID (アカウントID)
 */
export type LibsDomainModelInterfaceAuthLoginRequestAccountId = string | null;

export interface LibsDomainModelInterfaceAuthLoginRequest {
  /** ユーザーID (アカウントID) */
  account_id?: LibsDomainModelInterfaceAuthLoginRequestAccountId;
  /** 認証コード (2次元バーコードでログイン使用する際に使用) */
  authentication_code?: LibsDomainModelInterfaceAuthLoginRequestAuthenticationCode;
  /** パスワード */
  password?: LibsDomainModelInterfaceAuthLoginRequestPassword;
  /** 
        参照元アプリケーション
        0: トモプラホーム
        1: 光村の国語映像資料 トモプラムービー
        2: 形成的評価 きそのたしかめCBT 国語
        3: 光村の単元テスト 到達度評価シート 国語
        4: デジタル小学新国語辞典
        5: デジタル小学新漢字辞典
        6: あかねこローマ字スキルコネクト
        7: あかねこローマ字スキルコネクト タイピングチャレンジ
        8: あかねこ漢字スキルコネクト光村図書版
        9: あかねこ漢字スキルコネクト東京書籍版
        10: あかねこ漢字スキルコネクト教育出版版
        11: あかねこひらがな・すうじスキルコネクト光村図書版
        12: あかねこひらがな・すうじスキルコネクト東京書籍版
        13: あかねこひらがな・すうじスキルコネクト教育出版版
        14: あかねこカタカナスキルコネクト
        15: あかねこ計算スキルコネクト標準版
        16: あかねこ計算スキルコネクト東京書籍版
        17: あかねこ計算スキルコネクト啓林館版
         */
  referrer_application: number;
}

export type LibsDomainModelInterfaceAuthIssueAccountResponseStartDate =
  Date | null;

export type LibsDomainModelInterfaceAuthIssueAccountResponseExpirationDate =
  Date | null;

export interface LibsDomainModelInterfaceAuthIssueAccountResponse {
  authentication_key: string;
  expiration_date: LibsDomainModelInterfaceAuthIssueAccountResponseExpirationDate;
  release_code_user_uuid: string;
  start_date: LibsDomainModelInterfaceAuthIssueAccountResponseStartDate;
}

/**
 * 解除コード
 */
export type LibsDomainModelInterfaceAuthIssueAccountRequestReleaseCode =
  | string
  | null;

export interface LibsDomainModelInterfaceAuthIssueAccountRequest {
  /** 
        参照元アプリケーション
        0: トモプラホーム
        1: 光村の国語映像資料 トモプラムービー
        2: 形成的評価 きそのたしかめCBT 国語
        3: 光村の単元テスト 到達度評価シート 国語
        4: デジタル小学新国語辞典
        5: デジタル小学新漢字辞典
        6: あかねこローマ字スキルコネクト
        7: あかねこローマ字スキルコネクト タイピングチャレンジ
        8: あかねこ漢字スキルコネクト光村図書版
        9: あかねこ漢字スキルコネクト東京書籍版
        10: あかねこ漢字スキルコネクト教育出版版
        11: あかねこひらがな・すうじスキルコネクト光村図書版
        12: あかねこひらがな・すうじスキルコネクト東京書籍版
        13: あかねこひらがな・すうじスキルコネクト教育出版版
        14: あかねこカタカナスキルコネクト
        15: あかねこ計算スキルコネクト標準版
        16: あかねこ計算スキルコネクト東京書籍版
        17: あかねこ計算スキルコネクト啓林館版
         */
  referrer_application: number;
  /** 解除コード */
  release_code?: LibsDomainModelInterfaceAuthIssueAccountRequestReleaseCode;
}

export interface LibsDomainModelInterfaceAuthCheckOnetimeCodeResponse {
  user_uuid: string;
}

export interface WordsLookedUpRanking {
  rank: number;
  words: string;
}

export interface WordsLookedUpRandom {
  rank: number;
  words: string;
}

export interface Words {
  researchers: string;
  words: string;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export interface UserPreferenceEntity {
  profile_icon: number;
  theme_color: number;
}

export type UserCoreGrade = number | null;

export type UserCoreClassName = string | null;

export type UserCoreAttendanceNo = number | null;

export interface UserCore {
  attendance_no?: UserCoreAttendanceNo;
  class_name?: UserCoreClassName;
  grade?: UserCoreGrade;
  nick_name: string;
  user_name: string;
  user_type: number;
  user_uuid: string;
}

export type TestUnitFrequencyType =
  (typeof TestUnitFrequencyType)[keyof typeof TestUnitFrequencyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TestUnitFrequencyType = {
  初回: '初回',
  初回再: '初回再',
  直近: '直近',
  直近再: '直近再',
} as const;

export interface TestUnit {
  frequency_type: TestUnitFrequencyType;
  teaching_units: TeachingUnitForTest;
  test_date: Date;
  total: number;
}

export type TeachingUnitItemForTestResult =
  (typeof TeachingUnitItemForTestResult)[keyof typeof TeachingUnitItemForTestResult];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TeachingUnitItemForTestResult = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export interface TeachingUnitItemForTest {
  item_name: string;
  result: TeachingUnitItemForTestResult;
}

export type TeachingUnitItemForPretestResult =
  (typeof TeachingUnitItemForPretestResult)[keyof typeof TeachingUnitItemForPretestResult];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TeachingUnitItemForPretestResult = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;

export interface TeachingUnitItemForPretest {
  item_name: string;
  result: TeachingUnitItemForPretestResult;
}

export interface TeachingUnitForTest {
  items: TeachingUnitItemForTest[];
  teaching_unit_name: string;
}

export interface TeachingUnitForPretest {
  items: TeachingUnitItemForPretest[];
  teaching_unit_name: string;
}

export interface StudyTime {
  date: Date;
  study_time: number;
}

export type SchoolClassGrade = number | null;

export type SchoolClassClassName = string | null;

export interface SchoolClass {
  class_name: SchoolClassClassName;
  grade: SchoolClassGrade;
}

export type PreTestUnitFrequencyType =
  (typeof PreTestUnitFrequencyType)[keyof typeof PreTestUnitFrequencyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreTestUnitFrequencyType = {
  初回: '初回',
  初回再: '初回再',
  直近: '直近',
  直近再: '直近再',
} as const;

export interface PreTestUnit {
  frequency_type: PreTestUnitFrequencyType;
  teaching_units: TeachingUnitForPretest;
  test_date: Date;
  total: number;
}

export interface Municipalities {
  municipality_id: number;
  municipality_name: string;
}

export type MediaType = (typeof MediaType)[keyof typeof MediaType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;

export type LicenseEntityPath = string | null;

export interface LicenseEntity {
  expiration_date: Date;
  learning_contents: number;
  path?: LicenseEntityPath;
  status: number;
}

export type LearningHistoryForTestUserUuid = string | null;

export type LearningHistoryForTestSchoolClass = SchoolClass | null;

export interface LearningHistoryForTest {
  pretest: PreTestUnit[];
  school_class?: LearningHistoryForTestSchoolClass;
  test: TestUnit[];
  user_uuid?: LearningHistoryForTestUserUuid;
}

export interface KanjiDictionaryKLearningHistory {
  active_time: number;
  last_action_date: Date;
  school_class: SchoolClass;
  total_number_labels: number;
  total_number_medals: number;
  total_number_word: number;
  user_uuid: string;
}

export type JapaneseDictionaryLearningHistoryUserUuid = string | null;

export interface JapaneseDictionaryLearningHistory {
  active_time: number;
  last_action_date: Date;
  school_class: SchoolClass;
  total_number_correct: number;
  total_number_labels: number;
  total_number_medals: number;
  total_number_my_dictionary: number;
  total_number_word: number;
  total_number_word_quiz: number;
  user_uuid?: JapaneseDictionaryLearningHistoryUserUuid;
}

export interface HealthCheckResponse {
  message: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface ErrorResponse {
  message: string;
  status: number;
}

export interface DateData {
  day: number;
  medal_type: MediaType;
}

export interface LoginCalendar {
  date_data: DateData[];
  month: number;
  year: number;
}

export interface DailyData {
  access_data: AccessData[];
  study_date: Date;
  total_number: number;
}

export type ChildLastLoginDate = Date | null;

export type ChildGrade = number | null;

export type ChildClassName = string | null;

export type ChildAttendanceNo = number | null;

export interface Child {
  attendance_no?: ChildAttendanceNo;
  class_name?: ChildClassName;
  grade?: ChildGrade;
  last_login_date?: ChildLastLoginDate;
  nick_name: string;
  user_name: string;
  user_uuid: string;
}

export interface Children {
  school_class: SchoolClass;
  user: Child[];
}

export interface Category {
  category_grade: number;
  category_id: number;
  category_name: string;
}

export interface CBTCategory {
  cbt_category_grade: number;
  cbt_category_id: number;
  cbt_category_name: string;
}

export interface AccessData {
  number_studies: number;
  teaching_unit_name: string;
}
